### ISSUE TITLE
"annotation" directory for tutorial notebook

### ISSUE THREAD

**Issue by Y-ogativity** [BIMSBbioinfo/scregseg#6]
Hi,
Thank you for providing an interesting tool. I am trying to reproduce your results in the tutorial. Please let me know where I could find the bed files in the "annotation" directory (such as annotation/genesets/bcell.bed') that you used for Gene set enrichment analysis in the tutorial notebook 03?

Thanks,
Yohei

**Comment by wkopp** [comment]
Thank you, Yohei, for pointing that out.
I added the annotation directory to the repository.
Best,
Wolfgang
